clone_depth: 5

configuration:
  - Release
  - Debug

image: Visual Studio 2015
  
platform:
  - x64

build_script:
  - 'git submodule update --init --recursive'
  - ps: Invoke-WebRequest "https://github.com/chigraph/chigraph/releases/download/dependencies/llvm-4.0.0-$env{CONFIGURATION}-msvc14-win64.tar.xz" -OutFile third_party/llvm-%CONFIGURATION%.tar.xz
  - mkdir third_party/llvm-%CONFIGURATION%
  - cd third_party/llvm-%CONFIGURATION%
  - tar xf ../llvm-%CONFIGURATION%.tar.xz
  - cd ../..
  - mkdir build
  - cd build
  - cmake -G'Visual Studio 14 2015 Win64' -DCMAKE_BUILD_TYPE="%CONFIGURATION%" ..
  - msbuild chigraph.sln

 