sudo: required

arch:
    packages:
        - base
        - base-devel
        - llvm
        - cmake
        - boost
        - python-pip
    script:
        - sudo pip install git+git://github.com/eddyxu/cpp-coveralls.git
        - cmake . -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage -std=c++11 -lstdc++"
        - make
        - CTEST_OUTPUT_ON_FAILURE=1 make test
        - coveralls --exclude /usr/ --exclude test/ --exclude third_party --exclude libchig/include/chig/json.hpp --include libchig/ --include chig/
        
script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
