language: cpp
sudo: required
dist: trusty



            
before_script:
- sudo apt-get update
- sudo apt-get upgrade
- sudo apt-get install g++-4.9 cmake libboost-all-dev llvm-3.7 llvm-3.7-dev libllvm3.7
- sudo pip install --user git+git://github.com/eddyxu/cpp-coveralls.git
after_success:
- cmake . -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage"
- make
- make test
- coveralls
env: COMPILER=g++-4.9
