sudo: required
dist: trusty

language: cpp

compiler:
  - clang-3.8
  - clang-3.9
  - g++-5

env:
  - LLVM_ROOT=/usr/lib/llvm-3.8/lib/cmake/llvm BUILD_TYPE=Debug    QT_VER=56
  - LLVM_ROOT=/usr/lib/llvm-3.8/lib/cmake/llvm BUILD_TYPE=Release  QT_VER=56
  - LLVM_ROOT=/usr/lib/llvm-3.9/lib/cmake/llvm BUILD_TYPE=Debug    QT_VER=56
  - LLVM_ROOT=/usr/lib/llvm-3.9/lib/cmake/llvm BUILD_TYPE=Release  QT_VER=56

before_install:
  - 'sudo add-apt-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main"'
  - 'sudo add-apt-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"'
  - 'sudo wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -'
  - 'sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test'
  - 'sudo add-apt-repository -y ppa:beineri/opt-qt561-trusty'
  - sudo apt-get update
  - sudo apt-get install -y llvm-3.8-dev clang-3.8 llvm-3.9-dev clang-3.9 g++-5 cmake python3 python3-pip  qt56base qt56tools qt56svg qt56script
  - source /opt/qt56/bin/qt56-env.sh
  - sudo pip install git+git://github.com/eddyxu/cpp-coveralls.git
  - cd ..
  - 'git clone https://anongit.kde.org/extra-cmake-modules.git'
  - mkdir extra-cmake-modules/build
  - cd extra-cmake-modules/build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - sudo make install
  - cd ../..
  - 'git clone https://anongit.kde.org/kitemviews.git'
  - mkdir kitemviews/build
  - cd kitemviews/build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - sudo make install -j8
  - cd ../..
  - 'git clone https://anongit.kde.org/kwidgetsaddons.git'
  - mkdir kwidgetsaddons/build
  - cd kwidgetsaddons/build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - sudo make install -j8
  - cd ../..
  - 'git clone https://anongit.kde.org/karchive.git'
  - mkdir karchive/build
  - cd karchive/build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - sudo make install -j8
  - cd ../..
  - 'git clone https://anongit.kde.org/ki18n.git'
  - mkdir ki18n/build
  - cd ki18n/build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - sudo make install -j8
  - cd ../..
  - 'git clone https://anongit.kde.org/kiconthemes.git'
  - mkdir kiconthemes/build
  - cd kiconthemes/build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - sudo make install -j8
  - cd ../..
  - 'git clone https://anongit.kde.org/ktextwidgets.git'
  - mkdir ktextwidgets/build
  - cd ktextwidgets/build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - sudo make install -j8
  - cd ../..
  - 'git clone https://anongit.kde.org/kxmlgui.git'
  - mkdir kxmlgui/build
  - cd kxmlgui/build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - sudo make install -j8
  - cd ../..
  - cd chigraph
  - cmake . -DLLVM_ROOT=$LLVM_ROOT -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage"
  - make -j4
  - CTEST_OUTPUT_ON_FAILURE=1 make test
  - coveralls --exclude /usr/ --exclude test/ --exclude third_party --exclude libchig/include/chig/json.hpp --include libchig/ --include chig/
