language: cpp
dist: trusty

addons: 
  apt: 
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.7 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.6 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.5 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'ppa:presslabs/gitfs'
    packages:
      - build-essential
      - libedit-dev
      - llvm-3.5-dev
      - llvm-3.6-dev
      - llvm-3.7-dev
      - llvm-3.8-dev
      - llvm-3.9-dev
      - llvm-4.0-dev
      - libclang-3.5-dev
      - libclang-3.6-dev
      - libclang-3.7-dev
      - libclang-3.8-dev
      - libclang-3.9-dev
      - libclang-4.0-dev
      - lldb-3.5-dev
      - lldb-3.6-dev
      - lldb-3.7-dev
      - lldb-3.8-dev
      - liblldb-3.9-dev
      - liblldb-4.0-dev
      - ninja-build
      - g++-5
      - g++-6
      
matrix: 
  include: 

    # sneak in 1 osx one so we can see it early
    - os: osx
      osx_image: xcode8.2
      env: BUILD_TYPE=Debug
    
    - env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.5
    - env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.6
    - env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.7
    - env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Release   QT_VERSION=571 LLVM_VERSION=3.8
    - env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Debug     QT_VERSION=58  LLVM_VERSION=3.9
    - env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Release   QT_VERSION=58  LLVM_VERSION=4.0

    - os: osx
      osx_image: xcode8.2
      env: BUILD_TYPE=Release
    - os: osx
      osx_image: xcode8.1
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode8.1
      env: BUILD_TYPE=Release
    - os: osx
      osx_image: xcode8
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode8
      env: BUILD_TYPE=Release
    - os: osx
      osx_image: xcode7.3
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode7.3
      env: BUILD_TYPE=Release
      
        
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/


install: 
  - ./.travis/install.sh

script:
  - ./.travis/build.sh
