language: cpp
sudo: required
dist: trusty

matrix:
    include:
        - os:linux
        compiler: gcc
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['g++-4.9']
            before_script:
                - pip install --user git+git://github.com/eddyxu/cpp-coveralls.git
            after_success:
                - cmake . -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage"
                - make
                - make test
                - coveralls
            env: COMPILER=g++-4.9
