sudo: required
language: cpp
dist: trusty

addons: 
  apt: 
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7


matrix: 
  include: 
    - compiler: gcc
      env: CXX=g++5 CC=gcc5 QT_BASE=57 BUILD_TYPE=Debug
    - compiler: clang
      env: CXX=clang++-3.7 CC=clang-3.7 QT_BASE=57 BUILD_TYPE=Debug
    - compiler: gcc
      env: CXX=g++5 CC=gcc5 QT_BASE=57 BUILD_TYPE=Release
    - compiler: clang
      env: CXX=clang++-3.7 CC=clang-3.7 QT_BASE=57 BUILD_TYPE=Release

before_install:
  - 'sudo add-apt-repository ppa:beineri/opt-qt57-trusty -y'
  - sudo apt-get update

install: 
  - sudo apt-get install qt57base qt57script qt57declarative qt57tools ninja-build
  - source /opt/qt57/bin/qt57-env.sh
  - ./scripts/build_frameworks.sh $BUILD_TYPE Ninja

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - make -j`nproc`

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: YihGytt5BxAEKxSuj9SqcMbMSOBMQpdsmQBNsOQnx0PopxFj73q+Nx9AMqC06TdXerK22D+PXubxCKjqtjf1OCeVaG5X+WGsaMBVt02isMpcQjxRzvTORpIQ+AsTFAq2eFALfVSFHqjwiom2esCcm/2hPN4i5v1wti9OSL11tjAD/gyfthK3NDEgY/ccb+69C3sdJu0QcSTSwEjAWOIsP2KSFsMDghyVUia07+tVtisaF6NR6mClCXkeSI5zTlAt7Nd8LzUGvhUWs+TKf4UIdLKgEH2NtwQjR9chkNsT6xMpfErz6Wx7Uawb377ASYA9w7b3gW/Xqo/mDClPc5Y0DKQhKzp1EZesrpNambI/O7Sr/b7tbJm4Bu3W0wfpfwyrxSYjUOTST1Gu0OjszT33yWymSzLu1v32Na4DRo8YR6hmH0SjBBPwbRt5AQQSdiMbfHdpUHkNOyqLqlE/YTJkvzHKoY4TUSqMR1xVUZBFdFXmAgoXzR3SxZ0k2rGyWZ9Y5xNBD5ZSQ0R/cY7KKQ2Ctv0e9bW2Z5L5kNXkUeRiZa/MKoydNqVeOjkiV2fRb2HEOBS2s8FPk8tAFFyp+fCh6h2gCQhM5X22wSmQVk08IqogmD9bh6MM/zqNkJ2FTCJMpR0LpctbalVo2cFZgh1cbSM0YMg7y5xIV9ToyK2asrA=
  file: Chigraph-x86_64-$(git describe --tags --always).AppImage
  on:
    repo: russelltg/chigraph
