sudo: required
dist: trusty

language: cpp

compiler:
  - clang-3.8
  - clang-3.9
  - g++-5

env:
  - LLVM_ROOT=/usr/lib/llvm-3.8/lib/cmake/llvm BUILD_TYPE=Debug
  - LLVM_ROOT=/usr/lib/llvm-3.8/lib/cmake/llvm BUILD_TYPE=Release
  - LLVM_ROOT=/usr/lib/llvm-3.9/lib/cmake/llvm BUILD_TYPE=Debug
  - LLVM_ROOT=/usr/lib/llvm-3.9/lib/cmake/llvm BUILD_TYPE=Release

before_install:
  - 'sudo add-apt-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main"'
  - 'sudo add-apt-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"'
  - 'sudo wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -'
  - 'sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test'
  - sudo apt-get update -qq
  - sudo apt-get install -y llvm-3.8-dev clang-3.8 llvm-3.9-dev clang-3.9 g++-5 qtbase5-dev cmake python3 python3-pip
  - sudo pip install git+git://github.com/eddyxu/cpp-coveralls.git
  - cd ..
  - 'git clone https://anongit.kde.org/kwidgetsaddons.git'
  - mkdir kwidgetsaddons/build
  - cd kwidgetsaddons/build
  - cmake ..
  - sudo make install
  - cd ../..
  - 'git clone https://anongit.kde.org/kxmlgui.git'
  - mkdir kxmlgui/build
  - cd kxmlgui/build
  - cmake ..
  - sudo make install
  - cd ../..
  - cd chigraph
  - cmake . -DLLVM_ROOT=$LLVM_ROOT -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage"
  - make -j4
  - CTEST_OUTPUT_ON_FAILURE=1 make test
  - coveralls --exclude /usr/ --exclude test/ --exclude third_party --exclude libchig/include/chig/json.hpp --include libchig/ --include chig/
