language: cpp
sudo: required
dist: trusty



            
before_script:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main
- sudo deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main
- sudo deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main
- sudo apt-get update
- sudo apt-get install g++-5 cmake libboost-all-dev -y
- sudo pip install --user git+git://github.com/eddyxu/cpp-coveralls.git
script:
- cmake . -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage" -DCMAKE_CXX_COMPILER=g++-5
- make
- make test
- coveralls
env: COMPILER=g++-4.9
